### ISSUE TITLE
standardise the brand

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/nottsjs.github.io#10]
we should use NottsJS everywhere now.  sometimes its nottsjs or NottsJs etc

also we should use a standard bio.

example: "A JavaScript community in Nottingham, UK" or "We are a non-profit, volunteer led organisation building a community around JavaScript in Nottingham, UK"

Places to confirm
* [x] Website
* [x] Ti.to
* [x] Twitter

**Comment by iancrowther** [comment]
or - We are a non-profit, volunteer led organisation building a community around JavaScript in Nottingham, UK

**Comment by iancrowther** [comment]
@joemckie - thoughts?

**Comment by nomad3k** [comment]
Add logo onto the page as well.

**Comment by iancrowther** [comment]
@nomad3k @grahamsmith @joemckie - can one of you pick this up please?

**Comment by iancrowther** [comment]
resolved
