### ISSUE TITLE
add jan speakers to website

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/nottsjs.github.io#24]

**Comment by iancrowther** [comment]
@grahamsmith @grahamsmith @joemckie

**Comment by nomad3k** [comment]
Content from here: https://github.com/nottsjs/speakers/milestones/Wednesday%2013th%20January%20-%202016

**Comment by iancrowther** [comment]
yep - not sure who to go with tho

**Comment by iancrowther** [comment]
ideally we have 2 seakers only as getting x3 per month is going to be a nightmare

**Comment by nomad3k** [comment]
Well, we have Joe and ukmadz, who hasn't confirmed yet.  Let's go with that and fallback to Lean Coffee / open discussion if ukmadz can't do it.  Actually we could use that as a fallback format for any booking issues.

**Comment by iancrowther** [comment]
works for me

**Comment by iancrowther** [comment]
resolved https://github.com/nottsjs/nottsjs.github.io/pull/32
