### ISSUE TITLE
add seo

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/nottsjs.github.io#3]

**Comment by grahamsmith** [comment]
This seems like it is done? There are Open Graph tags and Twitter plus meta. What are the acceptance criteria for this? Can someone advise please. @iancrowther @joemckie

**Comment by iancrowther** [comment]
honestly, im not sure.. would liek to see that validated tho

**Comment by iancrowther** [comment]
can we create a contact@notts.js analytics account and reconfigure

**Comment by iancrowther** [comment]
created a new GA account - https://github.com/nottsjs/planning/blob/master/SECRETS.md#google
