### ISSUE TITLE
Cloudflare HTTPS

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/nottsjs.github.io#44]
Redirect to https from http would be worth adding in your cloudflare config.

**Comment by jonathanKingston** [comment]
The redirections are under "page rules" and typing in the URL and selecting "always use https".

![selection_002](https://cloud.githubusercontent.com/assets/338988/12991787/c32485b8-d108-11e5-89fc-45df8ab771c6.png)

**Comment by iancrowther** [comment]
will do when I get 5 ;-)

**Comment by jonathanKingston** [comment]
<script>alert('This is a test for the demo later, ignore me - will delete');</script>

**Comment by Codesleuth** [comment]
Done it.
