### ISSUE TITLE
/ redirect issue

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/nottsjs.github.io#5]
www.nottsjs.org/ main page redirects to a different domain: nottsjs.org
You should check nottsjs.org instead!

**Comment by iancrowther** [comment]
https://github.com/nottsjs/nottsjs.github.io/blob/master/index.html#L29

**Comment by iancrowther** [comment]
can you take a look at this, not sure what best fix is

**Comment by joemckie** [comment]
It's likely to be a htaccess thing on github's side. Seems like they remove the www out of the url. Will check when I'm at a computer

**Comment by iancrowther** [comment]
ah ok, not high priority

**Comment by joemckie** [comment]
Nope, also likely not something we can fix on our side. I'd say it's not an
issue, personally

On Wednesday, 19 August 2015, Ian Crowther <notifications@github.com> wrote:

> ah ok, not high priority
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nottsjs/nottsjs.github.io/issues/5#issuecomment-132516235>
> .
>


-- 
Joe McKie
Web Developer / Designer
Mobile:  +44 (0) 7792 467 389
Email: joe@joemck.ie
Website: http://joemck.ie/
